[package]
name = "server"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

default-run = "server"

[dependencies]
async-trait = "0.1.60"
aws-config = "0.55.3"
aws-sdk-s3 = "0.28.0"
axum = "0.6.2"
axum-macros = "0.3.1"
chrono = { version = "0.4.23", default-features = false }
clap = { version = "4.2", features = ["derive"] }
futures = "0.3.28"
include_dir = { version = "0.7.3", features = ["metadata", "glob"] }
indoc = "2.0"
markdown = "1.0.0-alpha"
maud = { version = "0.25.0", features = ["axum"] }
miette = { version = "5.7", features = ["fancy"] }
mime_guess = "2.0"
opentelemetry = { version = "0.19.0", features = [
  "rt-tokio",
], default-features = false }
opentelemetry-otlp = { version = "0.12.0", features = [
  "http-proto",
  "reqwest-rustls",
  "reqwest-client",
], default-features = false }
path-absolutize = "3.0"
poise = "0.5.5"
reqwest = { workspace = true }
rss = { version = "2.0", features = ["validation"] }
sentry = { version = "0.31.5", default-features = false, features = [
  "rustls",
  "backtrace",
  "contexts",
  "panic",
  "tower",
  "reqwest",
] }
sentry-tower = { version = "0.31.5", features = ["http"] }
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.7.1"
serde_yaml = "0.9"
sqlx = { version = "0.7", features = [
  "sqlite",
  "runtime-tokio-rustls",
  "chrono",
] }
syntect = "5.0"
thiserror = "1.0"
tokio = { version = "1.21", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = "0.1.37"
tracing-opentelemetry = "0.19.0"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-tree = "0.2.2"
url = "2.4.0"
urlencoding = "2.1"
uuid = { version = "1.2", features = ["v4"] }

cacache = { version = "11.6.0", default-features = false, features = [
  "tokio-runtime",
] }
ssri = "9.0.0"
